#!/bin/bash
# M3_slice_time_correction.sh
#
# Single-subject slice timing correction prototype for MIDUS M3 data.
# The production version is slurm_M3_stc_parallel.sh (SLURM array job).
#
# The MIDUS data has a non-standard axis layout, so FSL's slicetimer requires
# axis swapping before and after correction:
#   1. Reorient to standard (fslreorient2std)
#   2. Swap axes so the slice dimension (dim1) becomes dim3 (FSL convention)
#   3. Run slicetimer with custom slice order (from extractSliceTiming.py)
#   4. Swap axes back to original layout
#   5. Restore original geometry header
#
# The corrected file overwrites the original in-place.
#
# Dependencies: FSL 6.0.7.10
# Slice order file: M3_slice_order.txt (generated by extractSliceTiming.py)

INPUT_FILE="/scratch/groups/fvlin/MIDUS/M3/M3_ImagingSession/sub-10036/func/sub-10036_task-EmotionRegulation_run-03_bold.nii.gz"
OUT_FILE="/scratch/groups/fvlin/MIDUS/M3/M3_ImagingSession/sub-10036/func/sub-10036_task-EmotionRegulation_run-03_bold.nii.gz"
TR=2.0
SLICE_ORDER="--ocustom=/home/users/aturnbu2/M3_slice_order.txt"

echo "  Starting slice time correction..."

ml fsl/6.0.7.10

# Step 0: Reorient to standard (optional but recommended)
fslreorient2std "$INPUT_FILE" temp_input.nii.gz

# Step 1: Swap axes so slice dim (dim1) becomes dim3
fslswapdim temp_input.nii.gz z y x temp_swapped.nii.gz

# Step 2: Slice time correction
slicetimer -i temp_swapped.nii.gz -o temp_stc.nii.gz -r $TR $SLICE_ORDER

# Step 3: Swap back to original axes
fslswapdim temp_stc.nii.gz z y x temp_output.nii.gz

# Step 4: Restore geometry from original
fslcpgeom "$INPUT_FILE" temp_output.nii.gz

ml fsl

# Step 5: Save final output
mv temp_output.nii.gz "$OUT_FILE"

# Cleanup
rm temp_input.nii.gz temp_swapped.nii.gz temp_stc.nii.gz

echo "  Slice time correction complete. Output saved as: $OUT_FILE"

